const promptsConstants = [
    "What is the last moment you feel joyful?",
    "What are five things you would like to do before you are 20 years old?",
    "Is it ever okay to lie? Why do you think so?",
    "Would you rather be beautiful, smart, or athletic? Why?",
    "Write about a day you'd like to forget.",
    "What is one thing in your bucket list that you can do right now?",
    "What's a new self-care habit you want to develop?",
    "Describe a perfect day of pampering and relaxation for you.",
    "How do you know when you need a break? What do you do?",
    "Write about a time when taking care of yourself improved your situation.",
    "What’s a guilty pleasure that you secretly love?",
    "How do you destress after a long week?",
    "Reflect on an activity that always improves your mood.",
    "What’s your go-to comfort food and why?",
    "Describe your evening routine. How does it help you unwind?",
    "What role does physical exercise play in your mental health?",
    "What is the last moment you feel joyful?",
    "What are five things you would like to do before you are 20 years old?",
    "Is it ever okay to lie? Why do you think so?",
    "Would you rather be beautiful, smart, or athletic? Why?",
    "Write about a day you'd like to forget.",
    "What is one thing in your bucket list that you can do right now?",
    "What's a new self-care habit you want to develop?",
    "Describe a perfect day of pampering and relaxation for you.",
    "How do you know when you need a break? What do you do?",
    "Write about a time when taking care of yourself improved your situation.",
    "What’s a guilty pleasure that you secretly love?",
    "How do you destress after a long week?",
    "Reflect on an activity that always improves your mood.",
    "What’s your go-to comfort food and why?",
    "Describe your evening routine. How does it help you unwind?",
    "What role does physical exercise play in your mental health?",
    "If you could live in any fictional universe, where would you choose and why?",
    "What's something you've always wanted to learn but haven't had the chance to yet?",
    "If you could have any superpower, what would it be and how would you use it?",
    "What's a skill you wish you were better at and why?",
    "Describe your dream vacation. Where would you go and what would you do?",
    "If you could have dinner with any historical figure, who would it be and what would you talk about?",
    "Write about a time when you overcame a fear. How did you do it?",
    "What's your favorite quote and why does it resonate with you?",
    "If you could only listen to one song for the rest of your life, what would it be and why?",
    "What's something you're proud of accomplishing this year?",
    "If you could swap lives with anyone for a day, who would it be and why?",
    "Describe your dream job. What would you be doing and why does it appeal to you?",
    "Write about a time when you had to make a difficult decision. How did you decide?",
    "If you could travel back in time and give your younger self one piece of advice, what would it be?",
    "What's something you wish more people knew about you?",
    "If you could visit any place in the world, where would you go and why?",
    "What's a hobby or activity you've always wanted to try but haven't yet?",
    "Write about a moment when you felt truly inspired. What inspired you?",
    "What's a book or movie that has had a big impact on your life?",
    "Describe your ideal day off. How would you spend it?",
    "If you could solve one world problem, what would it be and how would you do it?",
    "What's a small act of kindness that has made a big difference in your life?",
    "Write about a time when you had to step out of your comfort zone. What did you learn?"
]

module.exports = promptsConstants